# -*- coding: utf-8 -*-
"""EDA Football

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TY70pIsdd7h-omw3gQTP_CSMfPMrGy5Q
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (9, 5)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

df = pd.read_csv ('/content/top250_football.csv')
df

df.info()

df.describe()

df_new=df.copy()

df_new

#An outlier was found during our intial analysis phase.
# A player's age was 0. This outier might have occured due to data being incorrectly entered.
# We solved this problem by removing the particular players data.

df_new.drop(df_new[df_new.Age < 15].index, inplace=True)

df_new.info()

sc = ['Position','Age','League_from','League_to','Season','Transfer_fee']

df_new=df_new[sc]

df_new

#Plotting a histogram for the age of players
plt.figure(figsize=(12, 6))
plt.title("Age of players")
plt.xlabel('Age')
plt.ylabel('Players')

plt.hist(df_new.Age, bins=np.arange(15,40,1), color='black');

"""Inference:- From the histogram of age of players plotted, it is seen that the maximum number of players which are transferred are in the 25 age group. The number of players who are young have more number of transfers compared to old players. It is also seen that after the age of 20, the number of transfers for players suddenly increases."""

df_new.Season

Season_counts = df_new.Season.value_counts(sort=False)
Season_counts

top_Position = df_new.Position.value_counts().head(15)
top_Position

plt.figure(figsize=(12,6))
plt.xticks(rotation=75)
plt.title('Position')
sns.barplot(top_Position.index, top_Position);

"""Inferenece:- The most sought after position is the forward position while the least sought after is goalkeepers. This is because a football team generally consists of around 12 forwards at any given point of time. On the contrary, a team only consists of 3 goalkeepers which makes the demand for goalkeepers very less. Also forwards are more prone to injury due to the nature of the game so teams require more number of forwards."""

df_new.League_from

df_new.League_to

Lfr = df_new.League_from.value_counts().head(15)
Lfr

Lto = df_new.League_to.value_counts().head(15)
Lto

fig, axes = plt.subplots(1, 2, figsize=(16, 8))

axes[0].set_title('Players left the League')
axes[0].set_xlabel('Players')
axes[0].set_ylabel("League")
axes[0].tick_params(labelrotation=75)
sns.barplot(Lfr.index, Lfr,ax=axes[0]);

axes[1].set_title('Players joined the League')
axes[1].set_xlabel('Players')
axes[1].set_ylabel("League")
plt.xticks(rotation=75)
sns.barplot(Lto.index, Lto);

"""Inference:- Maximum number of players left the Premier League but similarly many players joined the PL as well. In total the number of players in the league does not change that much. Number of players who joined the italian league Serie A is more than the number of players who left. This can be attributed to the fact that teams like juventus, AC milan, Inter, Napoli are coming into the spotlight for some years now. Also these teams have also been winning european cups. Number of players who left spanish league La Liga has always been on the higher side because in spanish football, the players are trained in their respective teams academies only. In recent times, players joining league 1 has increased due to the saudi takeover of teams like Paris Saint germain"""

#Valuation for top leagues

league_valuation = df_new.groupby('League_to')[['Transfer_fee']].mean().sort_values('Transfer_fee', ascending=False)
l = league_valuation.head(15)
l

plt.figure(figsize=(20,10))
plt.xticks(rotation=75)
plt.ylabel('Currency')
plt.title('League valuation')
plt.legend(['Transfer_fee']);
plt.bar(l.index, l.Transfer_fee);

"""Inference:- Highest league valuation (based on transfer fees) is of La Liga. This is because teams in La Liga train their players in their own academies. This is why these players are sought after by many clubs, making their transfer fees high. Premier league is a very monetarily rich club and thus it is able to produce more quality footballers, making its valuation high. The USA based MLS is also on the top 10 highest league valuations as america has started investing heavily in football."""

#Scatter Plot for the transfer fees for the ages

plt.figure(figsize=(20,15))
plt.ylim(10, 40)
sns.scatterplot('Transfer_fee','Age', data=df_new,size="Transfer_fee", hue = "Transfer_fee",sizes=(100, 300) );

"""Inference:- This Visualization shows us the how the transfer fees if affected because of the age. The high transfer fees is given to young players of age 20-25. As the players start getting old, their transfer fees decreases. However there are some exceptions like Cristiano Ronaldo who still has a high transfer fees at the age of 37. The highest ever recorded transfer fees was given to Neymar Junior at a record 222 million pounds. His age at the time of transfer was 25."""

rtfr = df.Team_from.value_counts().head(15)
rtfr

rtto = df.Team_to.value_counts().head(15)
rtto

fig, axes = plt.subplots(1, 2, figsize=(16, 8))
axes[0].set_title('Players left the Team')
axes[0].set_xlabel('Players')
axes[0].set_ylabel("Teams")
axes[0].tick_params(labelrotation=75)
sns.barplot(rtfr.index, rtfr,ax=axes[0]);
axes[1].set_title('Players joined the Team')
axes[1].set_xlabel('Players')
axes[1].set_ylabel("Team")
plt.xticks(rotation=75)
sns.barplot(rtto.index, rtto)

"""Inference:- Inter Milan from Serie A has the maximum number of players leaving and joining. This is because the team in part few years has gone through many managerial changes and every manager brings in a different play style to the team. This results in many players being left out and ultimately leaving the team while many players being bought to fit the managerial style. Spurs saw more people leaving their team and compartively less people joining as spurs are trophyless since the past 3 decades and no players wish to jooin them. We hypothesized that Real Madrid would have the maximum number of plaeyrs joining their team but from this we can see that english and italian teams are more sough after than spanish teams."""

Team_valuation = df.groupby('Team_to')[['Transfer_fee']].mean().sort_values('Transfer_fee', ascending=False)
tv = Team_valuation.head(15)
tv

#Richest clubs in the world

plt.figure(figsize=(20,10))
plt.xticks(rotation=75)
plt.ylabel('Currency')
plt.title('Team valuation')
plt.legend(['Transfer_fee']);
plt.bar(tv.index, tv.Transfer_fee);

"""Inference:- SIPG (Shangai Port FC) is the highest valued club in terms of the transfer fee spent. We hypothesized Real Madrid or Manchester United to be the team with the most spending and team valuation. However SIPG sits at the top. The reason fro this is that China has heavily invested into its football and SIPG is an example of it. SIPG has seen some major international playerss transfers like Iniesta from Barcelona, Oscar from Chelsea, Hulk from Brazil, etc. This makes SIPG the richest team in terms of transfer fees. However we see that only one chinese club is amongst the richest clubs. Rest all are English, Spanish< French and Italian clubs. This shows that the chinese league is not that high valued yet."""

#Transfer values for season

S = df_new.groupby('Season')[['Transfer_fee']].mean().sort_values('Season', ascending=True)

plt.figure(figsize=(12,6))
plt.title("Transfer values for season")
plt.ylabel('Value Transfer Fee')
plt.xlabel('Players')
plt.plot(S.index, S, 'b-x', linewidth=4, markersize=12, markeredgewidth=4, markeredgecolor='navy');
plt.xticks(rotation=75);

"""Inference:- The transfer fees throughout the seaons has remained constant on 100 million dollars. However from the seaon 2013-2014 the transfer fees for players increased due to more money coming into the teams and leagues. The transfer fees peaked in the season 2017-2018 as that season neymar transferred for 222 million dollars to psg, making it the highest transfer of all time. The average transfer value throughout seasons is 100 million dollars."""

#Do people like staying in the same leagues or no?

cc = np.where(df_new["League_from"] == df_new["League_to"], True, False)

df1 = pd.DataFrame(data=cc, columns=["Same League"])
df1 = df1.value_counts()

plt.figure(figsize=(12,6))
plt.pie(df1, labels=['Different league','Same league'], autopct='%1.1f%%', startangle=180);

"""Inference:- It is an assumption that people feel comfortable playing in their leagues and do not wish to go out of their countries. However this assumption is not true as around 67.5 persent of players chose to go to different leagues. This can be attributed to many factors such as willingness to explore football oversees, higher transfer salaries in other leagues or not wanting to transfer to rivals in the same league."""

Lfr_mon= df.groupby('League_from')[['Transfer_fee']].mean().sort_values('Transfer_fee', ascending=False)
Lfr_mon = Lfr_mon.head(15)
Lfr_mon

Lto_mon= df.groupby('League_to')[['Transfer_fee']].mean().sort_values('Transfer_fee', ascending=False)
Lto_mon = Lto_mon.head(15)
Lto_mon

"""Inference:- Many players leave major leagues like the french league and the portugal league and prefer to play in Spanish and English league due to hgiher salaries, better footballing levels and training. This is the reason why the La Liga and the premier league have the highest join rates.

Conclusion

Thus we have drawn the following inferences from the dataset:

1) the best football leagues are Premier league, serie A, LaLagia as these leagues have players with best Transfer fee and club valuation. Even the players are drawn to these top leagues

2) The highest number of transfer occurs for forwards followed by the defenders. Even their transfer fee is the highest

3) Most number of transfers occurs between the age 22 to 25 and that is the age where the transfer fee is highest for any player

4) Every season the Transfer market is busy and the transfer market is growing year by year.

5) Players are willing to move to new leagues in search of new adventures.
"""